# Generated by Django 3.1.1 on 2020-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento_preventivo',
            old_name='auditado',
            new_name='terminado',
        ),
        migrations.RemoveField(
            model_name='mantenimiento_preventivo',
            name='comentarios_auditor',
        ),
        migrations.AddField(
            model_name='mantenimiento_preventivo',
            name='duracion_horas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento_preventivo',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
