# Generated by Django 3.1.1 on 2020-11-12 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id_requisicion', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('enlace_concepto', models.CharField(max_length=255)),
                ('justificacion', models.TextField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField(default=0)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_estimada', models.DateField(null=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('aprobacion', models.BooleanField(default=False)),
                ('proveedor', models.CharField(max_length=255)),
                ('metodo_de_pago', models.CharField(max_length=255)),
                ('observaciones', models.TextField(default='', null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('id_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pugsealapp.hotel')),
                ('id_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
