# Generated by Django 3.1.3 on 2020-11-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitud',
        ),
    ]
