# Generated by Django 3.1.1 on 2020-11-27 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0002_auto_20201125_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento_preventivo',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='mantenimiento_preventivo',
            name='supervisado',
        ),
        migrations.RemoveField(
            model_name='mantenimiento_preventivo',
            name='terminado',
        ),
        migrations.AlterField(
            model_name='mantenimiento_preventivo',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
    ]
