# Generated by Django 3.1.1 on 2020-11-23 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0002_auto_20201122_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento_correctivo',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
