# Generated by Django 3.1.1 on 2020-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0002_requisicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicion',
            old_name='aprobacion',
            new_name='aprobacion_auditor',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='aprobacion_director_gral',
            field=models.BooleanField(default=False),
        ),
    ]
