# Generated by Django 3.1.1 on 2020-11-13 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0003_auto_20201112_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_estimada',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
