# Generated by Django 3.1.1 on 2020-11-23 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0003_auto_20201123_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento_correctivo',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
