# Generated by Django 3.1.1 on 2020-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0004_auto_20201127_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento_preventivo',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
