# Generated by Django 3.1.1 on 2020-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0005_auto_20201113_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='enlace_concepto',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='justificacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='metodo_de_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
