# Generated by Django 3.1.1 on 2020-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0005_mantenimiento_preventivo_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento_preventivo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
