# Generated by Django 3.1.1 on 2020-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugsealapp', '0006_auto_20201127_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento_preventivo',
            name='comentarios_auditor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento_preventivo',
            name='comentarios_encargado',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
